FROM alpine:latest

LABEL author="lemoncode21"
LABEL youtube="www.youtube.com/lemoncode21" website="ww.lemoncode21.com"

RUN mkdir hello

RUN echo "hello world" > "hello/helloworld.txt"

CMD cat "hello/helloworld.txt"
