version: "3.8"

services:
# short syntax
  mongodb-bind-1:
    image: mogo:latest
    container_name: mongodb-example-1
    ports:
      - "27017:17017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo1:/data/db"

# long syntax
  mongodb-bind-2:
    image: mogo:latest
    container_name: mongodb-example-2
    ports:
      - "27018:17017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: bind
        target: "./data-mongo2"
        source: "/data/db"
        read_only: false