version: "3.8"

services:
  fastapi-app:
    container_name: fastapi-app
    build:
      context: "."
      dockerfile: Dockerfile
    image: "fastapi-app:1.0.0"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s