version: "3.8"

services:
  fastapi-app:
    container_name: fastapi-app
    build:
      context: "."
      dockerfile: Dockerfile
    image: "fastapi-app:1.0.0"
    ports:
      - "8080:8080"
    environment:
      - MODE=local