Origin:
  author: Dan Brown
  language: English
  publication-date: 2017-10-03
  page: 461
  description: When billionaire researcher Edmond Kirsch it is up to Robert Langdon and Ambra Vidal to honor his memory by making public his findings concerning the origin of human life and its destiny.
